import os
from keyring import get_password
from werkzeug.utils import import_string
import keyring.backend
from keyrings.alt.file import PlaintextKeyring
from CryptoUsersService.helpers import log_info

DB = "users_service"
PORT = 27017
LOCAL_SERVER = "134.122.79.43"
KAFKA_BROKERS = "134.122.79.43:9092"
CENTRAL_SERVER = "134.122.79.43"
CENTRAL_MONGO_DATABASE = "crypto"
TRANSACTIONS_TOPIC_NAME = "transactions"
COMPUTED_NOTIFICATIONS_TOPIC_NAME = "computed_notifications"
USER_NOTIFICATIONS_TOPIC_NAME = "user_notifications"
LOCAL_MONGO_DATABASE = "users_service"
PRICES_TOPIC_NAME = "prices"


class BaseConfig(object):
    DEBUG = False
    TESTING = False
    CENTRAL_SERVER = CENTRAL_SERVER
    CENTRAL_MONGO_DATABASE = CENTRAL_MONGO_DATABASE
    CENTRAL_MONGO_USERNAME = ""
    CENTRAL_MONGO_PASSWORD = ""
    CENTRAL_PORT = PORT

    LOCAL_PORT = PORT
    LOCAL_SERVER = LOCAL_SERVER
    LOCAL_MONGO_DATABASE = LOCAL_MONGO_DATABASE
    LOCAL_MONGO_USERNAME = ""
    LOCAL_MONGO_PASSWORD = ""
    LOGS_PATH = 'CryptoUsersService/logs/CryptoUsersService.log'
    KAFKA_BROKERS = KAFKA_BROKERS
    TRANSACTIONS_TOPIC_NAME = TRANSACTIONS_TOPIC_NAME
    USER_NOTIFICATIONS_TOPIC_NAME = USER_NOTIFICATIONS_TOPIC_NAME
    COMPUTED_NOTIFICATIONS_TOPIC_NAME = COMPUTED_NOTIFICATIONS_TOPIC_NAME
    PRICES_TOPIC_NAME = PRICES_TOPIC_NAME

    PUSH_NOTIFICATIONS_SPLIT_INTO_SUBSETS = -1
    PUSH_NOTIFICATIONS_ASSIGN_TO_SUBSET = -1


class DevelopmentConfig(BaseConfig):
    DEBUG = False
    TESTING = False
    CENTRAL_SERVER = CENTRAL_SERVER
    CENTRAL_MONGO_DATABASE = CENTRAL_MONGO_DATABASE
    CENTRAL_MONGO_USERNAME = ""
    CENTRAL_MONGO_PASSWORD = ""
    CENTRAL_PORT = PORT
    LOCAL_PORT = PORT
    LOCAL_SERVER = LOCAL_SERVER
    LOCAL_MONGO_DATABASE = LOCAL_MONGO_DATABASE
    LOCAL_MONGO_USERNAME = ""
    LOCAL_MONGO_PASSWORD = ""
    LOGS_PATH = 'CryptoUsersService/logs/CryptoUsersService.log'
    KAFKA_BROKERS = KAFKA_BROKERS
    TRANSACTIONS_TOPIC_NAME = TRANSACTIONS_TOPIC_NAME
    USER_NOTIFICATIONS_TOPIC_NAME = USER_NOTIFICATIONS_TOPIC_NAME
    COMPUTED_NOTIFICATIONS_TOPIC_NAME = COMPUTED_NOTIFICATIONS_TOPIC_NAME
    PRICES_TOPIC_NAME = PRICES_TOPIC_NAME


    PUSH_NOTIFICATIONS_SPLIT_INTO_SUBSETS = -1
    PUSH_NOTIFICATIONS_ASSIGN_TO_SUBSET = -1

class ProductionConfig(BaseConfig):
    DEBUG = False
    TESTING = False
    CENTRAL_SERVER = CENTRAL_SERVER
    CENTRAL_MONGO_DATABASE = CENTRAL_MONGO_DATABASE
    CENTRAL_MONGO_USERNAME = ""
    CENTRAL_MONGO_PASSWORD = ""
    CENTRAL_PORT = PORT
    LOCAL_PORT = PORT
    LOCAL_SERVER = LOCAL_SERVER
    LOCAL_MONGO_DATABASE = LOCAL_MONGO_DATABASE
    LOCAL_MONGO_USERNAME = ""
    LOCAL_MONGO_PASSWORD = ""
    LOGS_PATH = 'CryptoUsersService/logs/CryptoUsersService.log'
    KAFKA_BROKERS = KAFKA_BROKERS
    TRANSACTIONS_TOPIC_NAME = TRANSACTIONS_TOPIC_NAME
    USER_NOTIFICATIONS_TOPIC_NAME = USER_NOTIFICATIONS_TOPIC_NAME
    COMPUTED_NOTIFICATIONS_TOPIC_NAME = COMPUTED_NOTIFICATIONS_TOPIC_NAME
    PRICES_TOPIC_NAME = PRICES_TOPIC_NAME

    PUSH_NOTIFICATIONS_SPLIT_INTO_SUBSETS = -1
    PUSH_NOTIFICATIONS_ASSIGN_TO_SUBSET = -1


config = {
    "development": "CryptoUsersService.config.DevelopmentConfig",
    "production": "CryptoUsersService.config.ProductionConfig",
    "default": "CryptoUsersService.config.DevelopmentConfig",
}


def configure_app():

    keyring.set_keyring(PlaintextKeyring())
    config_name = os.getenv('FLASK_ENV', 'CryptoUsersService.config.DevelopmentConfig')
    cfg = import_string(config_name)()
    cfg.LOCAL_MONGO_USERNAME = get_password('CryptoUsersService', 'LOCAL_MONGO_USERNAME')
    cfg.LOCAL_MONGO_PASSWORD = get_password('CryptoUsersService', cfg.LOCAL_MONGO_USERNAME)
    cfg.CENTRAL_MONGO_USERNAME = get_password('CryptoUsersService', 'CENTRAL_MONGO_USERNAME')
    cfg.CENTRAL_MONGO_PASSWORD = get_password('CryptoUsersService', cfg.CENTRAL_MONGO_USERNAME)


    return cfg
